name: Python application test with Github Actions

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install xvfb
      run: sudo apt-get install -y xvfb

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r requirements.txt -vvv

    - name: Install Playwright browsers
      run: xvfb-run -- playwright install

    - name: Check Python version
      run: python --version

    - name: Check pip version
      run: pip --version

    - name: List installed packages
      run: pip list

    - name: Run tests
      run: xvfb-run -- pytest tests/test_shopping_cart.py